# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-ci

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install build-essential gcc-multilib g++-multilib libzip-dev zlib1g lib32z1
  displayName: 'Install dependencies'

- script: |
    cd ports/gprs_a9
    make
  displayName: 'Build a9g'

