trigger:
- azure-ci

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive

- script: sudo apt-get install build-essential gcc-multilib g++-multilib libzip-dev zlib1g lib32z1
  displayName: 'Install dependencies'

- script: |
    cd ports/gprs_a9
    make
  displayName: 'Build a9g'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'ports/gprs_a9/hex/firmware_debug_full.lod'
    ArtifactName: 'gprs-a9-micropython-image'
    publishLocation: 'Container'
