pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive

- script: sudo apt-get install build-essential gcc-multilib g++-multilib libzip-dev zlib1g lib32z1
  displayName: 'Install dependencies'

- script: |
    cd ports/gprs_a9
    make
  displayName: 'Build a9g'

- task: GitHubRelease@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'github-pulkin'
    repositoryName: 'pulkin/micropython'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'a9-dev'
    releaseNotesSource: 'input'
    releaseNotes: 'Latest succesful build of `master`'
    assets: 'ports/gprs_a9/hex/firmware_debug_full.lod'
    assetUploadMode: 'replace'
    isPreRelease: true
    addChangeLog: false