trigger:
- azure-ci

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive

- script: sudo apt-get install build-essential gcc-multilib g++-multilib libzip-dev zlib1g lib32z1
  displayName: 'Install dependencies'

- script: |
    cd ports/gprs_a9
    make
  displayName: 'Build a9g'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'ports/gprs_a9/hex/firmware_debug_full.lod'
    artifact: 'gprs-a9-micropython-image'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'github-pulkin'
    repositoryName: 'pulkin/micropython'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'a9-dev'
    releaseNotesSource: 'input'
    assetUploadMode: 'replace'
    isDraft: true
    addChangeLog: false